version: "3.1"

services:
  controle-api:
    container_name: controle-api
    image: controle-api
    build:
      context: .
      dockerfile: ./ControleFinanceiro.API/Dockerfile
    ports:
      - '8000:80'
      #- '8001:443'
    restart: on-failure
    # depends_on:
      # - 'sme-db'
      # - 'sme-redis'
    env_file:
      - controle.env
    #volumes:
      #- ${USERPROFILE}\.aspnet\https:C:\https:ro
      #- ~/.aspnet/https:/https:ro