version: "3.5"

services:
  controle-db:
    container_name: controle-db
    image: postgres:14.1-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql/data
     # networks:
       # - rapnetwork
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: controle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  controle-api:
    container_name: controle-api
    image: controle-api
    build:
      context: .
      dockerfile: ./ControleFinanceiro.API/Dockerfile
    ports:
      - '8000:80'
    depends_on:
      - 'controle-db'
    env_file:
      - controle.env
      
volumes:
   postgresql-data:
   